apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-htqr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-htqr@sha256:9d4e470f8c1c44341d13084d3e5c7843a4923f58d71a77452dbc62e5c7354771
        name: my-nodejs
        resources: {}
status: {}
